### ISSUE TITLE
The start recording method was changed and requires an empty parameter list now

### ISSUE THREAD

**Issue by nfaliszewski** [krontech/chronos-examples#1]
The python start_stop_recording script will not start a recording anymore because there was a change made to the API where the startRecording method now requires an input parameter set. It can just be left blank, so the new line should be:

post = requests.post('http://192.168.12.1/control/startRecording', json = {})

**Comment by skronstein** [comment]
Fixed in commit a237ddc48acc052838c261a3f8185a31fc1e1fbd
